version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: cabinet_medical_db
    environment:
      POSTGRES_DB: cabinet_medical
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cabinet-network

  postgres-test:
    image: postgres:16-alpine
    container_name: cabinet_medical_db_test
    environment:
      POSTGRES_DB: cabinet_medical_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    networks:
      - cabinet-network

volumes:
  postgres_data:

networks:
  cabinet-network:
    driver: bridge

